name: eliud_pkg_etc
description: Eliud package for other extensions
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  eliud_core:
    path: ../eliud_core

  eliud_pkg_medium:
    path: ../eliud_pkg_medium

dev_dependencies:
  build_runner: "1.11.5"

  eliud_generator:
    path: ../eliud_generator

flutter:
  uses-material-design: true
