---
name: eliud_pkg_etc
description: Eliud package for other extensions
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_etc
version: 1.0.1+23
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  flutter:
    sdk: flutter
  eliud_core: ^1.0.20+1
  eliud_pkg_medium: ^1.0.1+23
  flutter_bloc: ^8.1.2
  cloud_firestore: ^4.6.0
  intl: ^0.18.1
  datetime_picker_formfield: ^2.0.0
  bloc: ^8.1.0
  meta: ^1.8.0
  equatable: ^2.0.5
  http: ^0.13.5
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator: 1.0.8
flutter:
  uses-material-design: true
platforms:
  android: null
  ios: null
  web: null
